using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(menuName = "Weapon", fileName = "Weapon")]
public class Weapon : ScriptableObject
{
    public enum WeaponType
    {
        Melee,
        Ranged,
        Magic
    }
    public WeaponType weaponType;
    public int damage;
    public float attacksPerSecond;
    public float range;

    //TODO: Add attack damage range(preset or autogenerated) and level requirement for weapons
}
